# Generated by Django 4.2.7 on 2023-11-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0003_product_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='places',
            new_name='old',
        ),
    ]
