# Generated by Django 4.2.7 on 2023-11-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0008_remove_order_products_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='yourappname.product')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='yourappname.size')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='yourappname.color')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='yourappname.product')),
            ],
        ),
    ]
