# Generated by Django 4.2.7 on 2023-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yourappname', '0009_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='admin', max_length=255)),
                ('contact', models.CharField(default=0, max_length=255)),
                ('message', models.CharField(default=0, max_length=1000)),
            ],
        ),
    ]
